# Site

title: Git and the Centralized Workflow
handouts:
#  - worksheet.ipynb
#  - worksheet.Rmd
tag: v0.2
lesson: 3
instructor: Ian Carroll
authors:
  - Ian Carroll

# Slides

slide_sorter:
  - intro
  - goals
  - git
  - reproducible
#  - workflows
  - terms
  - repo
  - merge
#  - paths
  - collab
  - resolve
  - conclude
  
#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v2.0/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
